apiVersion: apps/v1
kind: Deployment
metadata:
  name: AlbanianQuora  # Replace with your app name
  namespace: dotnetapp  # Optionally specify a namespace
spec:
  replicas: 3  # Number of pods to run
  selector:
    matchLabels:
      app: AlbanianQuora
  template:
    metadata:
      labels:
        app: AlbanianQuora
    spec:
      containers:
      - name: AlbanianQuora
      image: <pushbeckend>:latest